name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production

      - name: Deploy to Vercel
        run: npx vercel@latest --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --name=doodle-lab
